### ISSUE TITLE
Insert a Final Newline option

### ISSUE THREAD

**Issue by soneymathew** [khell/flow-to-ts#2]
Hello maintainer(s),

   `yarn run flow-to-ts --prettier .prettierrc --write --delete-source "$TARGET"`
   We are getting prettier errors after running the js files through the transpiler.
Is it possible to ensure that a final newline when the conversion is happening as an option or as default behaviour?

Thanks,
Soney

**Comment by khell** [comment]
Hi Soney,

I don't think Prettier has an option to add a newline. That we run Prettier at all is an artifact of the original implementation. Perhaps we could hook into an ESLint configuration in the future, but it's really outside the intended scope of this tool. Happy to accept a PR though.

Thank you!
