### ISSUE TITLE
Remove $Subtype and $Supertype when converting

### ISSUE THREAD

**Issue by Li0liQ** [khell/flow-to-ts#3]
`$Subtype` and `$Shape` generic flow types don't make sense in typescript.
The tool should remove them, i.e. `$Subtype<Type>` -> `Type`.

See https://github.com/Microsoft/TypeScript/issues/2710#issuecomment-266808185 .

**Comment by khell** [comment]
`$Shape` is an alias of `Partial`: https://github.com/piotrwitek/utility-types/blob/master/src/utility-types.ts#L134 In Flow it marks all the properties of a type optional, likewise with its TS equivalent. Can you please elaborate on why it doesn't make sense? Maybe we should change it directly to `Partial` and skip the `utility-types` alias.

Agreed with `$Subtype`. I don't think that's something we currently handle at all so it is output as-is. I'll add a case for it.

**Comment by khell** [comment]
Completed here, thanks!
https://github.com/khell/flow-to-ts/pull/8
